world:
  name: "futuro_map"
  auto-create: true

map:
  size: 1000
  water-level: 58
  border-size: 80

layers:
  bedrock-y: 0
  stone: 10
  dirt: 4

features:
  tree-chance-per-chunk: 0.65
  lake-chance-per-chunk: 0.08
  pasture-chance-per-chunk: 0.20
