# REAL_HOURS = usa horas/dias do mundo real.
# TICKS = usa ticks do servidor no mundo (fullTime).
time:
  mode: REAL_HOURS

# Em REAL_HOURS, valor em horas (24 = 1 dia, 48 = 2 dias).
# Em TICKS, valor absoluto em ticks.
regeneration:
  threshold: 24

removal:
  threshold: 24
